[[exception]]
target = "https://tools.ietf.org/id/draft-ietf-quic-tls-32.txt#6.2"
quote = '''
An endpoint
MAY treat consecutive key updates as a connection error of type
KEY_UPDATE_ERROR.
'''
reason = '''
Returning this error would indicate that a key update is in progress, revealing information about the state of the connection.
'''

